# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /bin/cmake/bin/cmake

# The command to remove a file.
RM = /bin/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blokhtin/github/Simple

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blokhtin/github/Simple/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1487/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/bin/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blokhtin/github/Simple/build/CMakeFiles /home/blokhtin/github/Simple/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blokhtin/github/Simple/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess_lib

# Build rule for target.
chess_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess_lib
.PHONY : chess_lib

# fast build rule for target.
chess_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/build
.PHONY : chess_lib/fast

#=============================================================================
# Target rules for targets named SimpleChessEngine

# Build rule for target.
SimpleChessEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleChessEngine
.PHONY : SimpleChessEngine

# fast build rule for target.
SimpleChessEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/build
.PHONY : SimpleChessEngine/fast

#=============================================================================
# Target rules for targets named file_toucher

# Build rule for target.
file_toucher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 file_toucher
.PHONY : file_toucher

# fast build rule for target.
file_toucher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/file_toucher.dir/build.make CMakeFiles/file_toucher.dir/build
.PHONY : file_toucher/fast

Chess/Attacks.o: Chess/Attacks.cpp.o
.PHONY : Chess/Attacks.o

# target to build an object file
Chess/Attacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Attacks.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Attacks.cpp.o
.PHONY : Chess/Attacks.cpp.o

Chess/Attacks.i: Chess/Attacks.cpp.i
.PHONY : Chess/Attacks.i

# target to preprocess a source file
Chess/Attacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Attacks.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Attacks.cpp.i
.PHONY : Chess/Attacks.cpp.i

Chess/Attacks.s: Chess/Attacks.cpp.s
.PHONY : Chess/Attacks.s

# target to generate assembly for a file
Chess/Attacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Attacks.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Attacks.cpp.s
.PHONY : Chess/Attacks.cpp.s

Chess/Evaluation.o: Chess/Evaluation.cpp.o
.PHONY : Chess/Evaluation.o

# target to build an object file
Chess/Evaluation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Evaluation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Evaluation.cpp.o
.PHONY : Chess/Evaluation.cpp.o

Chess/Evaluation.i: Chess/Evaluation.cpp.i
.PHONY : Chess/Evaluation.i

# target to preprocess a source file
Chess/Evaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Evaluation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Evaluation.cpp.i
.PHONY : Chess/Evaluation.cpp.i

Chess/Evaluation.s: Chess/Evaluation.cpp.s
.PHONY : Chess/Evaluation.s

# target to generate assembly for a file
Chess/Evaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Evaluation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Evaluation.cpp.s
.PHONY : Chess/Evaluation.cpp.s

Chess/MoveGenerator.o: Chess/MoveGenerator.cpp.o
.PHONY : Chess/MoveGenerator.o

# target to build an object file
Chess/MoveGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/MoveGenerator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/MoveGenerator.cpp.o
.PHONY : Chess/MoveGenerator.cpp.o

Chess/MoveGenerator.i: Chess/MoveGenerator.cpp.i
.PHONY : Chess/MoveGenerator.i

# target to preprocess a source file
Chess/MoveGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/MoveGenerator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/MoveGenerator.cpp.i
.PHONY : Chess/MoveGenerator.cpp.i

Chess/MoveGenerator.s: Chess/MoveGenerator.cpp.s
.PHONY : Chess/MoveGenerator.s

# target to generate assembly for a file
Chess/MoveGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/MoveGenerator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/MoveGenerator.cpp.s
.PHONY : Chess/MoveGenerator.cpp.s

Chess/MovePicker.o: Chess/MovePicker.cpp.o
.PHONY : Chess/MovePicker.o

# target to build an object file
Chess/MovePicker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/MovePicker.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/MovePicker.cpp.o
.PHONY : Chess/MovePicker.cpp.o

Chess/MovePicker.i: Chess/MovePicker.cpp.i
.PHONY : Chess/MovePicker.i

# target to preprocess a source file
Chess/MovePicker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/MovePicker.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/MovePicker.cpp.i
.PHONY : Chess/MovePicker.cpp.i

Chess/MovePicker.s: Chess/MovePicker.cpp.s
.PHONY : Chess/MovePicker.s

# target to generate assembly for a file
Chess/MovePicker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/MovePicker.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/MovePicker.cpp.s
.PHONY : Chess/MovePicker.cpp.s

Chess/Perft.o: Chess/Perft.cpp.o
.PHONY : Chess/Perft.o

# target to build an object file
Chess/Perft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Perft.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Perft.cpp.o
.PHONY : Chess/Perft.cpp.o

Chess/Perft.i: Chess/Perft.cpp.i
.PHONY : Chess/Perft.i

# target to preprocess a source file
Chess/Perft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Perft.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Perft.cpp.i
.PHONY : Chess/Perft.cpp.i

Chess/Perft.s: Chess/Perft.cpp.s
.PHONY : Chess/Perft.s

# target to generate assembly for a file
Chess/Perft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Perft.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Perft.cpp.s
.PHONY : Chess/Perft.cpp.s

Chess/Position.o: Chess/Position.cpp.o
.PHONY : Chess/Position.o

# target to build an object file
Chess/Position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Position.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Position.cpp.o
.PHONY : Chess/Position.cpp.o

Chess/Position.i: Chess/Position.cpp.i
.PHONY : Chess/Position.i

# target to preprocess a source file
Chess/Position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Position.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Position.cpp.i
.PHONY : Chess/Position.cpp.i

Chess/Position.s: Chess/Position.cpp.s
.PHONY : Chess/Position.s

# target to generate assembly for a file
Chess/Position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Position.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Position.cpp.s
.PHONY : Chess/Position.cpp.s

Chess/Quiescence.o: Chess/Quiescence.cpp.o
.PHONY : Chess/Quiescence.o

# target to build an object file
Chess/Quiescence.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Quiescence.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Quiescence.cpp.o
.PHONY : Chess/Quiescence.cpp.o

Chess/Quiescence.i: Chess/Quiescence.cpp.i
.PHONY : Chess/Quiescence.i

# target to preprocess a source file
Chess/Quiescence.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Quiescence.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Quiescence.cpp.i
.PHONY : Chess/Quiescence.cpp.i

Chess/Quiescence.s: Chess/Quiescence.cpp.s
.PHONY : Chess/Quiescence.s

# target to generate assembly for a file
Chess/Quiescence.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Quiescence.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Quiescence.cpp.s
.PHONY : Chess/Quiescence.cpp.s

Chess/Settings.o: Chess/Settings.cpp.o
.PHONY : Chess/Settings.o

# target to build an object file
Chess/Settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Settings.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Settings.cpp.o
.PHONY : Chess/Settings.cpp.o

Chess/Settings.i: Chess/Settings.cpp.i
.PHONY : Chess/Settings.i

# target to preprocess a source file
Chess/Settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Settings.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Settings.cpp.i
.PHONY : Chess/Settings.cpp.i

Chess/Settings.s: Chess/Settings.cpp.s
.PHONY : Chess/Settings.s

# target to generate assembly for a file
Chess/Settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_lib.dir/build.make CMakeFiles/chess_lib.dir/Chess/Settings.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/Settings.cpp.s
.PHONY : Chess/Settings.cpp.s

Chess/main.o: Chess/main.cpp.o
.PHONY : Chess/main.o

# target to build an object file
Chess/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/main.cpp.o
.PHONY : Chess/main.cpp.o

Chess/main.i: Chess/main.cpp.i
.PHONY : Chess/main.i

# target to preprocess a source file
Chess/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/main.cpp.i
.PHONY : Chess/main.cpp.i

Chess/main.s: Chess/main.cpp.s
.PHONY : Chess/main.s

# target to generate assembly for a file
Chess/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleChessEngine.dir/build.make CMakeFiles/SimpleChessEngine.dir/Chess/main.cpp.s
.PHONY : Chess/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... file_toucher"
	@echo "... SimpleChessEngine"
	@echo "... chess_lib"
	@echo "... Chess/Attacks.o"
	@echo "... Chess/Attacks.i"
	@echo "... Chess/Attacks.s"
	@echo "... Chess/Evaluation.o"
	@echo "... Chess/Evaluation.i"
	@echo "... Chess/Evaluation.s"
	@echo "... Chess/MoveGenerator.o"
	@echo "... Chess/MoveGenerator.i"
	@echo "... Chess/MoveGenerator.s"
	@echo "... Chess/MovePicker.o"
	@echo "... Chess/MovePicker.i"
	@echo "... Chess/MovePicker.s"
	@echo "... Chess/Perft.o"
	@echo "... Chess/Perft.i"
	@echo "... Chess/Perft.s"
	@echo "... Chess/Position.o"
	@echo "... Chess/Position.i"
	@echo "... Chess/Position.s"
	@echo "... Chess/Quiescence.o"
	@echo "... Chess/Quiescence.i"
	@echo "... Chess/Quiescence.s"
	@echo "... Chess/Settings.o"
	@echo "... Chess/Settings.i"
	@echo "... Chess/Settings.s"
	@echo "... Chess/main.o"
	@echo "... Chess/main.i"
	@echo "... Chess/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

