name: CMake Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -S ${{runner.workspace}}/Simple/Tests -B ${{runner.workspace}}/Simple/Tests/build -G "Visual Studio 17 2022"

    - name: Build
      working-directory: ${{runner.workspace}}/Simple/Tests/build
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{runner.workspace}}/Simple/Tests/build
      run: ctest -E EPD -V
