name: CMake Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE/Tests -B ${{runner.workspace}}/Tests/build

    - name: Build
      working-directory: ${{runner.workspace}}/Tests/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/Tests/build
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: ${{runner.workspace}}/Tests/build/test-results/**/*.xml
