name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: gcc:15
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up dependencies
      run: |
        apt-get update
        apt-get install -y wget unzip g++ make git cmake

    - name: Building the project
      working-directory: ${{runner.workspace}}/Simple
      run: |
        mkdir build
        cmake -DBUILD_TESTS=True -DCMAKE_BUILD_TYPE=Release -B build
        cmake --build build -t SCE_tests

    - name: Run tests
      working-directory: ${{runner.workspace}}/Simple/build
      run: |
        ulimit -s unlimited
        ctest -E "BestMove.WinAtChess"
