name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip sudo g++ make git cmake

    - name: Install glog
      run: |
        git clone https://github.com/google/glog.git
        cd glog && cmake -S . -B build -G "Unix Makefiles"
        cmake --build build
        sudo cmake --build build --target install

    - name: Building the project
      working-directory: ${{runner.workspace}}/Simple
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make

    - name: Run tests
      working-directory: ${{runner.workspace}}/Simple/build
      run: |
        ctest
        
    - name: Generate coverage report
      working-directory: ${{runner.workspace}}/Simple/build
      run: |
        make coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage_report       
